org: sewidat
app: projectx
service: users

frameworkVersion: "2 || 3"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  environment:
    tableName: ${self:custom.tableName}
  httpApi:
    cors: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.tableName}"

plugins:
  - serverless-package-common
  - serverless-plugin-webpack
custom:
  webpack:
    config: config/webpack.config.js
    series: true # run Webpack in series, useful for large projects. Defaults to false.
  packageCommon:
    common:
      - "../common"
  tableName: usersTable
functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /hello
          method: GET
  postUser:
    handler: api.putUser
    events:
      - httpApi:
          path: /users
          method: POST
          authorizer:
            type: aws_iam
  getUser:
    handler: api.getUser
    events:
      - httpApi:
          path: /user
          method: GET
  rmUser:
    handler: api.rmUser
    events:
      - httpApi:
          path: /user
          method: DELETE
  editUserx:
    handler: api.editUserx
    events:
      - httpApi:
          path: /userx
          method: PATCH
  editUser:
    handler: api.editUser
    events:
      - httpApi:
          path: /user
          method: PATCH
  scanUserByID:
    handler: api.scanByID
    events:
      - httpApi:
          path: /users
          method: GET
